development:
  adapter: postgresql
  encoding: unicode
  database: database-dev
  pool: 5
  username: mateusluizfb
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: database-test
  pool: 5
  username: mateusluizfb
  password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: database-production
#   pool: 5
#   username:
#   password:
