# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fe69fddd234f6e087841399936978fef5446859b26672d1c5165db6cbcc8fdf01b94c79e7f2e3908d651fdcdf49b7747f0a461d07b3e7b8f8d19b5626bbdfbb

test:
  secret_key_base: 3aa6643d6c3f684602d9396725151b6ecf50aa05e86ee6186c8414ed33e6f867021082a8c2abb0489a003f424798915692b240ddab6fe6851d94ad3a812fe088

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
